FORMAT: 1A
HOST: HOST:/127.0.0.1:8000

# Foregt & Reset Password 

Sending of a Mail to reset the password and Reset for password are done through this API.

##  Reset Mail Sending [/api/auth/sendPasswordResetLink]


### Reset Password Link in Mail [POST]

Here user will get request to his registered mail account to reset his account password.

+ Request (application/json) from client side
   
  
    [
    {
        "email":"gurukiran8861110488@gmail.com"
    }
    ]

     
    + Headers
            Content-Type: "application/json",
            type:"application/json",
            

                       
          
          
+ Response 200 (application/json)


    If email is present in database then mail will be sent
            
            
            {
                
              "data": "Reset Email is send successfully, please check your inbox."
                       
                        }

+ Response 401 (application/json)
  + Headers
            Content-Type: "application/json",
            type:"application/json",
           
If email it is not present in the database
            
                
             {
                 "message": "email not found in database"
            }




            
                       



## Password Reset [/api/auth/resetPassword]
### Reset Password [POST]

In this API password of user will be reset and new passwor will be added in that place. 

+ Request (application/json) from client side

                       [
                       {
                        
                        "resetToken" : nk3XWytDJD99pQ0X6kZQueJIn9Craww0eMRwVn8a
                        "email":"gurukiran8861110488@gmail.com",
                        "password": "********"
                        "password_confirmation":"********"

                       }
                       ]
                       
{
       
+ Response 200 (application/json)        
          If credentials are is correct then that account will be updated with new password
          
        

          {
             "data": "Password has been updated."
           }

         

{
{
+ Header

  type: application/json

}

}
+ Response 442 (application/json)  
        If Credentials are wrong then 

          {
              "error": "Either your email or token is wrong."
}